
//------------------------------------------------------------------------------
// This file was generated using the Faust compiler (https://faust.grame.fr),
// and the Faust post-processor (https://github.com/jpcima/faustpp).
//
// Source: bbba_gui.dsp
// Name: bbba
// Description: 
// Author: Klaus Scheuermann
// Copyright: 
// License: GPLv3+
// Version: 0.30
//------------------------------------------------------------------------------






#pragma once

#define DISTRHO_PLUGIN_NAME "bbba"
#define DISTRHO_PLUGIN_URI  "https://github.com/trummerschlunk/BigBlueBetterAudio"

#define DISTRHO_PLUGIN_IS_RT_SAFE      1
#define DISTRHO_PLUGIN_NUM_INPUTS      2
#define DISTRHO_PLUGIN_NUM_OUTPUTS     2

enum Parameters {
    // inputs
    kParameter_sb_strength,
    kParameter_sb_target_spectrum_0,
    kParameter_sb_target_spectrum_1,
    kParameter_sb_target_spectrum_2,
    kParameter_sb_target_spectrum_3,
    kParameter_sb_target_spectrum_4,
    kParameter_sb_target_spectrum_5,
    kParameter_sb_target_spectrum_6,
    kParameter_sb_target_spectrum_7,
    kParameter_voice_isolation_intensity,
    kParameter_pre_gain,
    kParameter_sbmb_strength,
    kParameter_vad_ext,
    kParameter_leveler_target,
    kParameter_leveler_scale,
    kParameter_mb_exp_strength,
    kParameter_mb_strength,
    kParameter_mb_exp_thresh,
    kParameter_pre_lowcut,
    kParameter_vad_gate_thresh,
    kParameter_vad_smoothing_time,
    
    // outputs
    kParameter_sb_meter__0,
    kParameter_sb_meter__1,
    kParameter_sb_meter__2,
    kParameter_sb_meter__3,
    kParameter_sb_meter__4,
    kParameter_sb_meter__5,
    kParameter_sb_meter__6,
    kParameter_sb_meter__7,
    kParameter_sb_gain__0,
    kParameter_sb_gain__1,
    kParameter_sb_gain__2,
    kParameter_sb_gain__3,
    kParameter_sb_gain__4,
    kParameter_sb_gain__5,
    kParameter_sb_gain__6,
    kParameter_sb_gain__7,
    kParameter_limiter_gain,
    kParameter_input_peak_channel_0,
    kParameter_input_peak_channel_1,
    kParameter_lufs_out_meter,
    kParameter_output_peak_channel_0,
    kParameter_output_peak_channel_1,
    kParameter_vad_meter,
    kParameter_leveler_gain,
    kParameter_mb_exp_meter0,
    kParameter_mb_exp_meter1,
    kParameter_mb_exp_meter2,
    kParameter_mb_exp_meter3,
    kParameter_mb_exp_meter4,
    kParameter_mb_exp_meter5,
    kParameter_mb_exp_meter6,
    kParameter_mb_exp_meter7,
    kParameter_mb_comp_gain_0,
    kParameter_mb_comp_gain_1,
    kParameter_mb_comp_gain_2,
    kParameter_mb_comp_gain_3,
    kParameter_mb_comp_gain_4,
    kParameter_mb_comp_gain_5,
    kParameter_mb_comp_gain_6,
    kParameter_mb_comp_gain_7,
    kParameter_vad_smoothing_meter,
    
    // terminator
    kParameterCount
};

enum Programs {
    kProgramCount
};

enum States {
    kStateCount
};

static constexpr const char* kParameterNames[62] = {
    // inputs
    "sb_strength",
    "spec 0",
    "spec 1",
    "spec 2",
    "spec 3",
    "spec 4",
    "spec 5",
    "spec 6",
    "spec 7",
    "VIintense",
    "PreGain",
    "sbmb_strength",
    "vad_ext",
    "target",
    "leveler_scale",
    "mb_exp_strength",
    "mb_strength",
    "mb_exp_thresh",
    "preLowcut_freq",
    "vad_g_thr",
    "vad_smoo_t",
    
    // ouputs
    "band  0",
    "band  1",
    "band  2",
    "band  3",
    "band  4",
    "band  5",
    "band  6",
    "band  7",
    "sb_gain  0",
    "sb_gain  1",
    "sb_gain  2",
    "sb_gain  3",
    "sb_gain  4",
    "sb_gain  5",
    "sb_gain  6",
    "sb_gain  7",
    "LimiterGR",
    "In 0",
    "In 1",
    "lufs_out",
    "Out 0",
    "Out 1",
    "vad_meter",
    "gain",
    "Exp0",
    "Exp1",
    "Exp2",
    "Exp3",
    "Exp4",
    "Exp5",
    "Exp6",
    "Exp7",
    "MBgr 0",
    "MBgr 1",
    "MBgr 2",
    "MBgr 3",
    "MBgr 4",
    "MBgr 5",
    "MBgr 6",
    "MBgr 7",
    "vad_smoo",
    
};

static constexpr const struct { float def, min, max; } kParameterRanges[62] = {
    // inputs
    { 50, 0, 100 },
    { -10, -20, 0 },
    { -5, -20, 0 },
    { -5, -20, 0 },
    { -8, -20, 0 },
    { -9, -20, 0 },
    { -10, -20, 0 },
    { -7, -20, 0 },
    { -4, -20, 0 },
    { 1, 0, 1 },
    { 0, -20, 20 },
    { 100, 0, 100 },
    { 1, 0, 1 },
    { -23, -60, 0 },
    { 1, 0, 1 },
    { 100, 0, 100 },
    { 50, 0, 100 },
    { 6, -12, 12 },
    { 42, 1, 400 },
    { 0.89999998, 0, 1 },
    { 50, 0, 1000 },
    
    // ouputs
    { 0, -40, 40 },
    { 0, -40, 40 },
    { 0, -40, 40 },
    { 0, -40, 40 },
    { 0, -40, 40 },
    { 0, -40, 40 },
    { 0, -40, 40 },
    { 0, -40, 40 },
    { 0, -12, 12 },
    { 0, -12, 12 },
    { 0, -12, 12 },
    { 0, -12, 12 },
    { 0, -12, 12 },
    { 0, -12, 12 },
    { 0, -12, 12 },
    { 0, -12, 12 },
    { 0, -12, 0 },
    { 0, -70, 0 },
    { 0, -70, 0 },
    { 0, -70, 0 },
    { 0, -70, 0 },
    { 0, -70, 0 },
    { 0, 0, 1 },
    { 0, -50, 50 },
    { 0, -12, 0 },
    { 0, -12, 0 },
    { 0, -12, 0 },
    { 0, -12, 0 },
    { 0, -12, 0 },
    { 0, -12, 0 },
    { 0, -12, 0 },
    { 0, -12, 0 },
    { 0, -12, 12 },
    { 0, -12, 12 },
    { 0, -12, 12 },
    { 0, -12, 12 },
    { 0, -12, 12 },
    { 0, -12, 12 },
    { 0, -12, 12 },
    { 0, -12, 12 },
    { 0, 0, 1 },
    
};

static constexpr const char* kParameterSymbols[62] = {
    // inputs
    "sb_strength",
    "sb_target_spectrum_0",
    "sb_target_spectrum_1",
    "sb_target_spectrum_2",
    "sb_target_spectrum_3",
    "sb_target_spectrum_4",
    "sb_target_spectrum_5",
    "sb_target_spectrum_6",
    "sb_target_spectrum_7",
    "voice_isolation_intensity",
    "pre_gain",
    "sbmb_strength",
    "vad_ext",
    "leveler_target",
    "leveler_scale",
    "mb_exp_strength",
    "mb_strength",
    "mb_exp_thresh",
    "pre_lowcut",
    "vad_gate_thresh",
    "vad_smoothing_time",
    
    // ouputs
    "sb_meter__0",
    "sb_meter__1",
    "sb_meter__2",
    "sb_meter__3",
    "sb_meter__4",
    "sb_meter__5",
    "sb_meter__6",
    "sb_meter__7",
    "sb_gain__0",
    "sb_gain__1",
    "sb_gain__2",
    "sb_gain__3",
    "sb_gain__4",
    "sb_gain__5",
    "sb_gain__6",
    "sb_gain__7",
    "limiter_gain",
    "input_peak_channel_0",
    "input_peak_channel_1",
    "lufs_out_meter",
    "output_peak_channel_0",
    "output_peak_channel_1",
    "vad_meter",
    "leveler_gain",
    "mb_exp_meter0",
    "mb_exp_meter1",
    "mb_exp_meter2",
    "mb_exp_meter3",
    "mb_exp_meter4",
    "mb_exp_meter5",
    "mb_exp_meter6",
    "mb_exp_meter7",
    "mb_comp_gain_0",
    "mb_comp_gain_1",
    "mb_comp_gain_2",
    "mb_comp_gain_3",
    "mb_comp_gain_4",
    "mb_comp_gain_5",
    "mb_comp_gain_6",
    "mb_comp_gain_7",
    "vad_smoothing_meter",
    
};

static constexpr const char* kParameterUnits[62] = {
    // inputs
    "%",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "dB",
    "",
    "",
    "LUFS",
    "",
    "%",
    "%",
    "dB",
    "",
    "",
    "ms",
    
    // ouputs
    "dB",
    "dB",
    "dB",
    "dB",
    "dB",
    "dB",
    "dB",
    "dB",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "LUFS",
    "",
    "",
    "",
    "dB",
    "dB",
    "dB",
    "dB",
    "dB",
    "dB",
    "dB",
    "dB",
    "dB",
    "dB",
    "dB",
    "dB",
    "dB",
    "dB",
    "dB",
    "dB",
    "dB",
    "",
    
};



